# Generated by Django 5.2.8 on 2025-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done'), ('Pending', 'Pending')], default='To Do', max_length=20),
        ),
    ]
