# Generated by Django 5.2.8 on 2025-11-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_task_assigned_to_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Done', 'Done'), ('Pending', 'Pending'), ('Missed', 'Missed')], default='Pending', max_length=20),
        ),
    ]
